---
title: "R Notebook"
output: html_notebook
---

# Bayesian Regression Modeling 

**NOTE THAT THIS CODE DOES NOT RUN ON MY MACOS M1 MACHINE! IT GIVES ME BELOW ERROR AND NOTHING CAN FIX IT!!! \
**`Error in unserialize(socklist[[n]]) : error reading from connection`

```{r}
renv::activate()
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(brms)
library(stringr)
library(glue)
library(ggplot2)
library(corrplot)
library(kableExtra)
library(caret)
library(kernlab)

library(dplyr)
# install.packages("devtools") # unless you have it already
library(devtools)
# install_github("jtextor/dagitty/r")
theme_set(theme_default())
# set rstan options
rstan::rstan_options(auto_write = TRUE)
options(mc.cores = 4)
parallel::detectCores()
```

## Data Transformation

```{r}
df <- read.csv("dataset/Latest Dataset.csv")

# transform ordinal variables to numeric
df$YrsExperience <- as.numeric(factor(df$YrsExperience, levels = c("<1 year", "1-3 years", "3-5 years", ">5 years")))
df$PRActivity <- as.numeric(factor(df$PRActivity, levels = c("Novice", "Intermediate", "Expert")))
df$GitHubActivity <- as.numeric(factor(df$GitHubActivity, levels = c("Infrequent", "Intermediate", "Experienced")))
df$BotExperience <- as.numeric(factor(df$BotExperience, levels = c("Inexperienced", "Intermediate", "Experienced")))

# transform categorical variables to numeric
for(scenario in c("ScenarioChoice1_Autonomy", "ScenarioChoice2_Autonomy")) {

  df[[scenario]] <- factor(recode(df[[scenario]],
                                     "Proactive" = "1", 
                                     "Neutral" = "2",
                                     "Reactive" = "3"),
                              levels=c("1","2","3"),ordered = T)
}
for(scenario in c("ScenarioChoice3_Persona", "ScenarioChoice4_Persona")) {
  df[[scenario]] <- factor(recode(df[[scenario]],
                                     "Factual" = "1", 
                                     "Neutral" = "2",
                                     "Personable" = "3"),
                              levels=c("1","2","3"),ordered = T)
}

df$ScenarioChoice1_Autonomy <- as.numeric(df$ScenarioChoice1_Autonomy)
df$ScenarioChoice2_Autonomy <- as.numeric(df$ScenarioChoice2_Autonomy)
df$ScenarioChoice3_Persona <- as.numeric(df$ScenarioChoice3_Persona)
df$ScenarioChoice4_Persona <- as.numeric(df$ScenarioChoice4_Persona)

```

## Model Descriptors

```{r}

m1_sc1 = 'ScenarioChoice1_Autonomy ~ GitHubActivity'
m2_sc1 = 'ScenarioChoice1_Autonomy ~ BotExperience + GitHubActivity + PRActivity + YrsExperience' # only technical 
m3_sc1 = 'ScenarioChoice1_Autonomy ~ ScenarioChoice3_Persona' # answer to SC3 (persona)

m1_sc2 = 'ScenarioChoice2_Autonomy ~ GitHubActivity'
m2_sc2 = 'ScenarioChoice2_Autonomy ~ BotExperience + GitHubActivity + PRActivity + YrsExperience' # only technical 
m3_sc2 = 'ScenarioChoice2_Autonomy ~ ScenarioChoice3_Persona' # answer to SC3 (persona)

m1_sc3 = 'ScenarioChoice3_Persona ~ GitHubActivity'
m2_sc3 = 'ScenarioChoice3_Persona ~ BotExperience + GitHubActivity + PRActivity + YrsExperience' # only technical 
m3_sc3 = 'ScenarioChoice3_Persona ~ ScenarioChoice1_Autonomy' # answer to SC3 (autonomy)

m1_sc4 = 'ScenarioChoice4_Persona ~ GitHubActivity'
m2_sc4 = 'ScenarioChoice4_Persona ~ BotExperience + GitHubActivity + PRActivity + YrsExperience' # only technical 
m3_sc4 = 'ScenarioChoice4_Persona ~ ScenarioChoice1_Autonomy' # answer to SC4 (autonomy)
```

## Modeling

```{r model inference scenario 1, echo=TRUE}

fit_sc1_m1 <- brm(
   chains = 1,
  formula = m1_sc1,
  data = df,
    file = 'models/fit_sc1_m1_new',
  file_refit = 'on_change',
  family = cumulative("probit"), #acat("probit"), #c
  iter = 100
)
fit_sc1_m2 <- brm(
  formula = m2_sc1,
  data = df,
    file = 'models/fit_sc1_m2',
    file_refit = 'on_change',
  family = cumulative("probit"), #acat("probit"), #c
  iter = 3000
)
fit_sc1_m3 <- brm(
  formula = m3_sc1,
  data = df,
  file = 'models/fit_sc1_m3',
      file_refit = 'on_change',

  family = cumulative("probit"), #acat("probit"), #c
  iter = 3000
)

```

```{r model inference scenario 2, results=F}

fit_sc2_m1 <- brm(
  formula = m1_sc2,
  data = df,
    file = 'models/fit_sc2_m1',
  file_refit = 'on_change',
  family = cumulative("probit"), #acat("probit"), #c
  iter = 3000
)
fit_sc2_m2 <- brm(
  formula = m2_sc2,
  data = df,
    file = 'models/fit_sc2_m2',
    file_refit = 'on_change',
family = cumulative("probit"), #acat("probit"), #c
  iter = 3000
)
fit_sc2_m3 <- brm(
  formula = m3_sc2,
  data = df,
  file = 'models/fit_sc2_m3',
    file_refit = 'on_change',
family = cumulative("probit"), #acat("probit"), #c
  iter = 3000
)

```

```{r model inference scenario 3, message=FALSE}

fit_sc3_m1 <- brm(
  formula = m1_sc3,
  data = df,
  file = 'models/fit_sc3_m1',
  file_refit = 'on_change',
  family = cumulative("probit"), #acat("probit"), #c
  iter = 3000
)
fit_sc3_m2 <- brm(
  formula = m2_sc3,
  file = 'models/fit_sc3_m2',
  data = df,
  file_refit = 'on_change',
  family = cumulative("probit"), #acat("probit"), #c
  iter = 3000
)
fit_sc3_m3 <- brm(
  formula = m3_sc3,
  data = df,
  file = 'models/fit_sc3_m3',
  file_refit = 'on_change',
  family = cumulative("probit"), #acat("probit"), #c
  iter = 3000
)

```

```{r model inference scenario 4}
# Sc3 and 4 are persona, Sc1 and 2 are autonomy.
# for (sc in scenario_lst ) {
#   for (model in model_lst) {
#     paste('

fit_sc4_m1 <- brm(
  formula = m1_sc4,
  data = df,
  file = 'models/fit_sc4_m1',
  file_refit = 'on_change',
  family = cumulative("probit"), #acat("probit"), #c
  iter = 3000
)
fit_sc4_m2 <- brm(
  formula = m2_sc4,
  data = df,
  file = 'models/fit_sc4_m2',
  file_refit = 'on_change',
  family = cumulative("probit"), #acat("probit"), #c
  iter = 3000
)
fit_sc4_m3 <- brm(
  formula = m3_sc4,
  data = df,
  file = 'models/fit_sc4_m3',
  file_refit = 'on_change',
  family = cumulative("probit"), #acat("probit"), #c
  iter = 3000
)
```
